apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Chart.Name }}-backend

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend

    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - {{ .Values.backend.affinity.zone1 }}
            - weight: 80
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - {{ .Values.frontend.affinity.zone2 }}

      containers:
        - name: django
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "{{ .Values.backend.resources.requests.cpu }}"
              memory: "{{ .Values.backend.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.backend.resources.limits.cpu }}"
              memory: "{{ .Values.backend.resources.limits.memory }}"

          envFrom:
            - configMapRef:
                name: {{ .Values.backend.env.configMapName }}
            - secretRef:
                name: {{ .Values.backend.env.secretName }}

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 2
