apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.env.secretName }}
  labels:
    app: {{ .Chart.Name }}-backend

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.backend.env.mysqlRootPassword }}
  DB_USER: {{ .Values.backend.env.dbUser }}
  DB_PASSWORD: {{ .Values.backend.env.dbPassword }}
