apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: {{ .Chart.Name }}-backend

spec:
  selector:
    app: {{ .Chart.Name }}-backend

  ports:
    - port: 8000
      targetPort: 8000

  type: {{ .Values.backend.service.type }}
