apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  annotations:
    description: "Make sure atleast one frontend pod is preventing from eviction during disruptions"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nginx
