apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    app: {{ .Chart.Name }}-frontend

spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-frontend

    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - {{ .Values.frontend.affinity.zone1 }}
            - weight: 80
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - {{ .Values.frontend.affinity.zone2 }}

      containers:
        - name: nginx
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "{{ .Values.frontend.resources.requests.cpu }}"
              memory: "{{ .Values.frontend.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.frontend.resources.limits.cpu }}"
              memory: "{{ .Values.frontend.resources.limits.memory }}"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
