apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    app: {{ .Chart.Name }}-frontend

spec:
  selector:
    app: {{ .Chart.Name }}-frontend

  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30080

  type: {{ .Values.frontend.service.type }}
